# Dockerfile

# 1. Usa una imagen base de Python
FROM python:3.10-slim

# 2. Establece el directorio de trabajo
WORKDIR /app

# 3. Copia el archivo de dependencias
COPY requirements.txt requirements.txt

# 4. Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copia el código fuente
COPY . .

CMD ["python", "main.py"]